# Generated by Django 5.1.4 on 2024-12-08 19:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_plantedtree_account_alter_plantedtree_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='created_at',
        ),
        migrations.AddField(
            model_name='account',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='plantedtree',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planted_trees', to='core.account'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='joined',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
