# Generated by Django 5.1.4 on 2024-12-09 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_account_created_at_account_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='members',
            field=models.ManyToManyField(related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
