# Generated by Django 5.1.4 on 2024-12-10 00:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_account_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='created',
        ),
        migrations.RemoveField(
            model_name='account',
            name='members',
        ),
        migrations.RemoveField(
            model_name='plantedtree',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(default='Sem descrição'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
